{% set name = "distributed" %}
{% set version = "2025.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: cf1d62a2c17a0a9fc1544bd10bb7afd39f22f24aaa9e3df3209c44d2cfb16703

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv --no-build-isolation
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:main
    - dask-ssh=distributed.cli.dask_ssh:main
    - dask-worker=distributed.cli.dask_worker:main
    - dask-spec=distributed.cli.dask_spec:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=62.6
    - versioneer 0.29
    - toml
  run:
    - python
    - click >=8.0
    - cloudpickle >=3.0.0
    - dask-core =={{ version }}
    - jinja2 >=2.10.3
    - locket >=1.0.0
    - msgpack-python >=1.0.2
    - packaging >=20.0
    - psutil >=5.8.0
    - pyyaml >=5.4.1
    - sortedcontainers >=2.0.5
    - tblib >=1.6.0
    - toolz >=0.11.2
    - tornado >=6.2.0
    - urllib3 >=1.26.5
    - zict >=3.0.0

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.comm
    - distributed.deploy
    - distributed.diagnostics
    - distributed.protocol
  commands:
    - pip check
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help
    - dask-spec --help
  requires:
    - pip

#Note: The build and dependency order for dask-distributed packages are as follows.
#      dask-core ---> dask-expr --->distributed --->dask

about:
  home: https://distributed.dask.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: A distributed task scheduler for Dask
  description: |
    Distributed is a lightweight library for distributed computing in Python.
    It extends both the concurrent.futures and dask APIs to moderate sized
    clusters.
  doc_url: https://distributed.dask.org
  dev_url: https://github.com/dask/distributed

extra:
  recipe-maintainers:
    - mrocklin
    - jcrist
    - martindurant
    - jakirkham
    - marcelotrevisani
    - ogrisel
    - tomaugspurger
    - jrbourbeau
