{% set name = "distributed" %}
{% set version = "2023.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5bdd4d15f3e7c8df98513b409753d46a39827a650620cc0c0c5ef2751561280

build:
  number: 0
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:main
    - dask-ssh=distributed.cli.dask_ssh:main
    - dask-worker=distributed.cli.dask_worker:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - versioneer 0.28
    - tomli 2.0.1
  run:
    - python
    - click >=8.0
    - cloudpickle >=1.5.0
    - dask-core {{ version }}
    - jinja2 >=2.10.3
    - locket >=1.0.0
    - msgpack-python >=1.0.0
    - packaging >=20.0
    - psutil >=5.7.2
    - pyyaml >=5.3.1
    - sortedcontainers >=2.0.5
    - tblib >=1.6.0
    - toolz >=0.10.0
    - tornado >=6.0.4
    - urllib3 >=1.24.3
    - zict >=2.2.0
  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.comm
    - distributed.deploy
    - distributed.diagnostics
    - distributed.protocol
  requires:
    - pip
  commands:
    - pip check
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

#Note: The build and dependency order for dask-distributed packages are as follows.
#      dask-core --->distributed --->dask

about:
  home: https://distributed.dask.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Distributed computing with Dask
  description: |
    Distributed is a lightweight library for distributed computing in Python.
    It extends both the concurrent.futures and dask APIs to moderate sized
    clusters.
  doc_url: https://distributed.dask.org
  dev_url: https://github.com/dask/distributed

extra:
  recipe-maintainers:
    - mrocklin
    - jcrist
    - martindurant
    - jakirkham
    - marcelotrevisani
    - ogrisel
    - tomaugspurger
    - jrbourbeau
  skip-lints:
    - python_build_tool_in_run