{% set name = "distributed" %}
{% set version = "2025.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 372c2f0c2faa890fc42188349969ba468161a9b356df49c4ca7d9a8d551a7ace

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:main
    - dask-ssh=distributed.cli.dask_ssh:main
    - dask-worker=distributed.cli.dask_worker:main

requirements:
  host:
    - python
    - pip
    - setuptools >=80
    - versioneer ==0.29
    - tomli
    - setuptools-scm
  run:
    - python
    - click >=8.0
    - cloudpickle >=3.0.0
    - dask-core =={{ version }}
    - jinja2 >=2.10.3
    - locket >=1.0.0
    - msgpack-python >=1.0.2
    - packaging >=20.0
    - psutil >=5.8.0
    - pyyaml >=5.4.1
    - sortedcontainers >=2.0.5
    - tblib >=1.6.0
    - toolz >=0.11.2
    - tornado >=6.2.0
    - urllib3 >=1.26.5
    - zict >=3.0.0

test:
  # Tests were tried from github sources but take too much time to even run, let alone debug
  # python(49771) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
  # Also tests are getting killed for using up the heap
  imports:
    - distributed
    - distributed.active_memory_manager
    - distributed.actor
    - distributed.batched
    - distributed.broker
    - distributed.cfexecutor
    - distributed.chaos
    - distributed.cli
    - distributed.client
    - distributed.cluster_dump
    - distributed.collections
    - distributed.comm
    - distributed.compatibility
    - distributed.config
    - distributed.core
    - distributed.counter
    - distributed.dashboard
    - distributed.deploy
    - distributed.diagnostics
    - distributed.diskutils
    - distributed.event
    - distributed.exceptions
    - distributed.gc
    - distributed.http
    - distributed.itertools
    - distributed.lock
    - distributed.metrics
    - distributed.multi_lock
    - distributed.nanny
    - distributed.node
    - distributed.objects
    - distributed.preloading
    - distributed.process
    - distributed.profile
    - distributed.protocol
    - distributed.publish
    - distributed.queues
    - distributed.recreate_tasks
    - distributed.scheduler
    - distributed.security
    - distributed.semaphore
    - distributed.shuffle
    - distributed.sizeof
    - distributed.spans
    - distributed.spill
    - distributed.stealing
    - distributed.system
    - distributed.system_monitor
    - distributed.threadpoolexecutor
    - distributed.utils
    - distributed.utils_comm
    - distributed.variable
    - distributed.versions
    - distributed.worker
  requires:
    - pip
  commands:
    - pip check
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

# Note: The build and dependency order for dask-distributed packages are as follows.
# dask-core -> dask-expr -> distributed -> dask
about:
  home: https://distributed.dask.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: A distributed task scheduler for Dask
  description: |
    Distributed is a lightweight library for distributed computing in Python.
    It extends both the concurrent.futures and dask APIs to moderate sized
    clusters.
  doc_url: https://distributed.dask.org
  dev_url: https://github.com/dask/distributed

extra:
  recipe-maintainers:
    - mrocklin
    - jcrist
    - martindurant
    - jakirkham
    - marcelotrevisani
    - ogrisel
    - tomaugspurger
    - jrbourbeau
