travis:
  secure:
    BINSTAR_TOKEN: gVbtxnfAdMuswhb2MsHs1bHrvCGZsCuBEj5LHiNeU0NTerJZkC8Vw/kYHebdwChqbGdOfY5iDS2RM4Qz9Bt0hbMmUo7r1c9VFdRkh/SSZ+V5UkBmETU7T5d1icwpqn1F34T3uRN7Eo/g++b27wAwaRoIOVFyX7H5OpbmAnSwaPGqgfozq30KTmyITcJbzebH3ooDljmkqha4mrv9KNOOJrNIXVklQQLuMg53JlAkfDDiXKvL2KHCtMJWgOd28G/bfpstFtj8sM0wmtFMGNGqVBaKzISAvHLpc0iC6jrV47dahiElez8Sp/wVemCYLDDHI6Y90CHHKQgXfhV1zcbIybPt5TP+/Ub5ATseI2zDqs6c2kpG7BTQPw0yjVKpPj6BfQpV5t7TQr5oDrLJJ7Kd0hhHSX5W6w7KOp7O0RvXAC60V5bpj8ks9lV4GOF56OIKp2G9euU8gS9JrpjzZ8Ldl1GgxqFp/isPzlzNkYkhBMEPNS3WAa5SAoE3MIqeBoux9BRM/CGwVzRQC2PrNIAiHYqzk/nUB4UxXkA1dESQnTEMExil0/n4HfqoZYjZhQQ0DiTuQd24UzK4HhWbwROmWTjy8CaCPDU5EenHlhEhlWfaAM0Okvi0U8O8DGuDEEBP6isVEz4vpV+1uXIX0ya+KxmGuxkn6HrQ8Jh+JOpGwls=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
